// new lines (count = 1):

__d("XAdsEventsManagerController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/events_manager2/",{privacy_mutation_token:{type:"String"},act:{type:"Int"},business_id:{type:"FBID"},global_scope_id:{type:"FBID"},conversion_ids:{type:"FBIDVector"},data_source_id:{type:"FBID"},data_source_type:{type:"String"},dialog:{type:"String"},nav_source:{type:"String"},rest:{type:"String"},view:{type:"String"},eligibility_check_result:{type:"String"},ads_objective:{type:"Enum",enumType:1},universal_link_uri:{type:"String"},origin:{type:"String"},optimization:{type:"Enum",enumType:1},event_name:{type:"String"},event_view:{type:"Enum",enumType:1},verify_event_name_id:{type:"FBID"},show_skan_aem_reporting_discrepancy_modal:{type:"String"}})}),null);

// old lines (count = 5)

__d("XBrandSafetyRootController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/brand_safety/{?page}/{?*childPath}",{privacy_mutation_token:{type:"String"},childPath:{type:"String"},act:{type:"Int"},ad_account_id:{type:"Int"},block_list_id:{type:"Int"},business_id:{type:"Int"},global_scope_id:{type:"FBID"},selected_section:{type:"String"},page:{type:"String"},nav_source:{type:"String"},allow_list_id:{type:"FBID"},placement_type:{type:"Enum",enumType:1},publisher_list_placement_type:{type:"Enum",enumType:1},follower_count:{type:"Enum",enumType:1},sort_by:{type:"Enum",enumType:1},block_lists_sort_by:{type:"Enum",enumType:1},start_date:{type:"String"},end_date:{type:"String"},creator_id:{type:"FBID"},search_query:{type:"String"},secondary_search_query:{type:"String"},publisher_status:{type:"Enum",enumType:1},pre_bid_control_id:{type:"FBID"},negative_keywords_id:{type:"FBID"}})}),null);
__d("XUFIDeleteCommentAndRemoveCommenterController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/ufi/deletecommentandremovecommenter/",{})}),null);
__d("XUFIDeleteCommentController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/ufi/delete/comment/",{privacy_mutation_token:{type:"String"}})}),null);
__d("XUFIReactionTooltipController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/ufi/reaction/tooltip/",{ft_ent_identifier:{type:"String",required:!0},seen_user_fbids:{type:"IntVector",defaultValue:[]},reaction_type:{type:"Enum",enumType:0},user_count:{type:"Int"}})}),null);
__d("XAdsEventsManagerController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/events_manager2/",{privacy_mutation_token:{type:"String"},act:{type:"Int"},business_id:{type:"FBID"},global_scope_id:{type:"FBID"},conversion_ids:{type:"FBIDVector"},data_source_id:{type:"FBID"},data_source_type:{type:"String"},dialog:{type:"String"},nav_source:{type:"String"},rest:{type:"String"},view:{type:"String"},eligibility_check_result:{type:"String"},ads_objective:{type:"Enum",enumType:1},universal_link_uri:{type:"String"},origin:{type:"String"},optimization:{type:"Enum",enumType:1},event_name:{type:"String"},event_view:{type:"Enum",enumType:1},verify_event_name_id:{type:"FBID"}})}),null);