// new lines (count = 5):

__d("XBusinessDownloadBusinessActivityLogsAsyncController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/download/activitylogs/",{business_id:{type:"FBID"},start_time:{type:"Int"},end_time:{type:"Int"}})}),null);
__d("XBusinessGetBusinessActivityLogsFileSizeController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/activitylogs/size/",{business_id:{type:"FBID",required:!0},start_time:{type:"Int",required:!0},end_time:{type:"Int",required:!0}})}),null);
__d("XBusinessDownloadUsersAndPermissionsAsyncController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/download/user_info/",{business_id:{type:"FBID"}})}),null);
__d("XAdvertiserEnforcementModalController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/accountquality/enforcement_modal/",{surface:{type:"Enum",required:!0,enumType:1},account_id:{type:"FBID"},is_creation_flow:{type:"Bool",defaultValue:!1}})}),null);
__d("XBusinessVerificationCreateOrContinueSubmissionController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/start_submission/",{legal_name:{type:"String"},email_domain:{type:"String"},website_url:{type:"String"},is_b2b:{type:"Bool",defaultValue:!1},tax_id_number:{type:"String"},registration_id_number:{type:"String"},state:{type:"String"},street2:{type:"String"},district:{type:"String"},phone_number:{type:"String"},country:{type:"String"},city:{type:"String"},street1:{type:"String"},postal_code:{type:"String"},business_id:{type:"FBID",required:!0},config:{type:"String"},indexed_id:{type:"String"},submission_context:{type:"Enum",defaultValue:"default",enumType:1}})}),null);

// old lines (count = 4)

__d("XBusinessEnterpriseEmailVerificationController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/enterprise/verification/email/",{nonce:{type:"String",required:!0}})}),null);
__d("XBusinessInviteSSOPeopleAsyncController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/invite/async/",{admin:{type:"String",required:!0},roles:{type:"StringVector"},business_id:{type:"FBID",required:!0},email:{type:"String",required:!0}})}),null);
__d("XBoostedAutomatedAdsBudgetMigrationMessageBoxController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/pages/boosted_automated_ads/budget_migration_message_box/",{boost_id:{type:"FBID",required:!0},page_id:{type:"FBID",required:!0}})}),null);
__d("XBusinessVerificationCreateOrContinueSubmissionController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/start_submission/",{legal_name:{type:"String"},email_domain:{type:"String"},website_url:{type:"String"},is_b2b:{type:"Bool",defaultValue:!1},tax_id_number:{type:"String"},registration_id_number:{type:"String"},state:{type:"String"},street2:{type:"String"},district:{type:"String"},phone_number:{type:"String",required:!0},country:{type:"String",required:!0},city:{type:"String",required:!0},street1:{type:"String",required:!0},postal_code:{type:"String",required:!0},business_id:{type:"FBID",required:!0},config:{type:"String"},indexed_id:{type:"String"},submission_context:{type:"Enum",defaultValue:"default",enumType:1}})}),null);