// new lines (count = 3):

__d("FBXAdsManagerFB4BResponsiveGenericPageController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/m/{*subpath}/",{subpath:{type:"String"},lead_source:{type:"String"},results:{type:"StringVector"},answers:{type:"StringVector"},assignment_id:{type:"FBID"},router:{type:"String"},form_id:{type:"FBID"},token:{type:"String"}})}),null);
__d("XVideoPermalinkController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/{vanity}/videos/{?set_token}/{video_id}/{?story_token}/{?*extra_junk}/",{extid:{type:"String"},mibextid:{type:"String"},rdid:{type:"String"},comment_id:{type:"IntOrPFBID"},photo_id:{type:"Int"},set_token:{type:"String"},type:{type:"Enum",defaultValue:3,enumType:0},link_share:{type:"String"},subject:{type:"Int"},object_id:{type:"Int"},opaque_cursor:{type:"String"},legacy_user_id:{type:"IntOrPFBID"},legacy_photo_id:{type:"Int"},video_id:{type:"Int"},notif_t:{type:"String"},is_notification_preview:{type:"Bool",defaultValue:!1},force_theater:{type:"Bool",defaultValue:!1},story_token:{type:"String"},reply_comment_id:{type:"IntOrPFBID"},comment_tracking:{type:"String"},vanity:{type:"String"},__tn__:{type:"String"},privacy_mutation_token:{type:"String"},t:{type:"Int"},flite:{type:"String"},__so__:{type:"Enum",enumType:1},__rv__:{type:"Enum",enumType:1},redirect:{type:"Bool",defaultValue:!0},depth:{type:"Int"},extra_junk:{type:"String"},comments_modal:{type:"Bool",defaultValue:!1},idorvanity:{type:"String"}})}),null);
__d("XVideoHomeFeedController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/watch/",{extid:{type:"String"},mibextid:{type:"String"},rdid:{type:"String"},comment_id:{type:"FBID"},cursor:{type:"String"},ref:{type:"String"},t:{type:"Int"},v:{type:"String"},external_log_id:{type:"String"},q:{type:"String"},__ft__:{type:"String"},page_id:{type:"FBID"},is_arltw:{type:"Bool",defaultValue:!1},comments_modal:{type:"Bool",defaultValue:!1}})}),null);

// old lines (count = 17)

__d("XCometFBMultiSiteJSErrorDetailsController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/ajax/js_error_details/",{})}),null);
__d("XCometFBMultiSiteJSErrorDetailsController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/ajax/js_error_details/",{})}),null);
__d("XPagesSettingsInstreamAdsBlockListTargetPageQueryController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/adbreaks/block_list/query/target_page/",{business_id:{type:"FBID",required:!0},value:{type:"String"},offset:{type:"Int",defaultValue:0},limit:{type:"Int",defaultValue:100}})}),null);
__d("XPagesSettingsInstreamAdsBlockListImportCSVController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/pages/admin/people_and_other_pages/block_list/import_csv/",{profile_id:{type:"FBID",required:!0},replace_block_lists:{type:"Bool",defaultValue:!1}})}),null);
__d("XAdsEventsManagerAdAccountGKController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/events_manager/ad_account_gk/",{ad_account_id:{type:"FBID",required:!0},gk_name:{type:"String",required:!0}})}),null);
__d("XPartnersOxsightsPredictionMetricsController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/actionable_insights/metrics/prediction/",{carrier_id:{type:"Int"},portal:{type:"Enum",enumType:1},ref:{type:"Enum",enumType:1},partner_id:{type:"Int"},metric_id:{type:"Enum",required:!0,enumType:1},session_id:{type:"String"},trace_id:{type:"String"}})}),null);
__d("XPartnersOxsightsPredictionMetricsController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/actionable_insights/metrics/prediction/",{carrier_id:{type:"Int"},portal:{type:"Enum",enumType:1},ref:{type:"Enum",enumType:1},partner_id:{type:"Int"},metric_id:{type:"Enum",required:!0,enumType:1},session_id:{type:"String"},trace_id:{type:"String"}})}),null);
__d("XPagesManagerProductDeleteController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/pages/content_tab/products/product_delete/",{catalog_item_ids:{type:"FBIDVector"}})}),null);
__d("XPagesManagerProductUpdateInventoryController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/pages/content_tab/products/update_inventory/",{product_group_ids:{type:"IntVector"},inventory_in_stock:{type:"Bool",defaultValue:!1}})}),null);
__d("XPagesManagerProductVariantsController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/pages/content_tab/product_variants/",{fetch_all_variants_for_item:{type:"Bool",defaultValue:!1},catalog_item_id:{type:"FBID",required:!0}})}),null);
__d("XPagePostExpirationController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/post/expiration/update/",{})}),null);
__d("XCRMManualContactCreationDialogController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/pages/crm/contact_creation/dialog/",{__asyncDialog:{type:"Int"},appointment_id:{type:"FBID"},contact_id:{type:"FBID"},first_name:{type:"String"},from_split_flow:{type:"Bool",defaultValue:!1},last_name:{type:"String"},page_id:{type:"FBID",required:!0},referrer:{type:"Enum",enumType:1},contact_card_surface:{type:"Enum",enumType:1}})}),null);
__d("XVideoPermalinkController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/{vanity}/videos/{?set_token}/{video_id}/{?story_token}/{?*extra_junk}/",{extid:{type:"String"},mibextid:{type:"String"},comment_id:{type:"IntOrPFBID"},photo_id:{type:"Int"},set_token:{type:"String"},type:{type:"Enum",defaultValue:3,enumType:0},link_share:{type:"String"},subject:{type:"Int"},object_id:{type:"Int"},opaque_cursor:{type:"String"},legacy_user_id:{type:"IntOrPFBID"},legacy_photo_id:{type:"Int"},video_id:{type:"Int"},notif_t:{type:"String"},is_notification_preview:{type:"Bool",defaultValue:!1},force_theater:{type:"Bool",defaultValue:!1},story_token:{type:"String"},reply_comment_id:{type:"IntOrPFBID"},comment_tracking:{type:"String"},vanity:{type:"String"},__tn__:{type:"String"},privacy_mutation_token:{type:"String"},t:{type:"Int"},flite:{type:"String"},__so__:{type:"Enum",enumType:1},__rv__:{type:"Enum",enumType:1},redirect:{type:"Bool",defaultValue:!0},depth:{type:"Int"},extra_junk:{type:"String"},comments_modal:{type:"Bool",defaultValue:!1},idorvanity:{type:"String"}})}),null);
__d("XAppSignalsConversionBitsSetAutoUnpauseStatusController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/app/events_manager/conversion_bits/set_auto_unpause_status/",{dataset_id:{type:"FBID"},auto_unpause_status:{type:"Bool",defaultValue:!1}})}),null);
__d("XAppSignalsConversionBitsSetMismatchMessageDismissController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/app/events_manager/conversion_bits/set_dismiss_conversion_mismatch/",{dataset_id:{type:"FBID"}})}),null);
__d("XAdsTargetingLookalikeToLookalikeContainerConversionController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/ads/targeting/lookalike_containers/lookalike_to_container_conversion/",{audiences:{type:"StringVector",required:!0},account_id:{type:"String",required:!0}})}),null);
__d("XVideoHomeFeedController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/watch/",{extid:{type:"String"},mibextid:{type:"String"},comment_id:{type:"FBID"},cursor:{type:"String"},ref:{type:"String"},t:{type:"Int"},v:{type:"String"},external_log_id:{type:"String"},q:{type:"String"},__ft__:{type:"String"},page_id:{type:"FBID"},is_arltw:{type:"Bool",defaultValue:!1},comments_modal:{type:"Bool",defaultValue:!1}})}),null);