// new lines (count = 13):

__d("XWebBloksAsyncRawController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/async/wbloks/fetch/",{appid:{type:"String",required:!0},params:{type:"String"},type:{type:"Enum",required:!0,enumType:1},debug_tooling_metadata_token:{type:"String"}})}),null);
__d("XWebBloksAsyncRawController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/async/wbloks/fetch/",{appid:{type:"String",required:!0},params:{type:"String"},type:{type:"Enum",required:!0,enumType:1},debug_tooling_metadata_token:{type:"String"}})}),null);
__d("XWebBloksAsyncRawController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/async/wbloks/fetch/",{appid:{type:"String",required:!0},params:{type:"String"},type:{type:"Enum",required:!0,enumType:1},debug_tooling_metadata_token:{type:"String"}})}),null);
__d("XDeveloperAppController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/apps/{app_id}/{?page}/{?tab}/{?view}/",{business_id:{type:"Int"},sub_tab:{type:"String"},app_id:{type:"Int",required:!0},page:{type:"Enum",enumType:1},tab:{type:"String"},view:{type:"String"},use_case_enum:{type:"Enum",enumType:1},add_on_enum:{type:"Enum",enumType:1},placement_id:{type:"Int"},active_placements_offset:{type:"Int"},disabled_placements_offset:{type:"Int"},blocked_placements_offset:{type:"Int"},alert_id:{type:"Int"},ref:{type:"String"},id:{type:"Int"},app_locale:{type:"String"},a_n:{type:"String"},c_n:{type:"String"},access_token:{type:"String"},new_app_email_pending:{type:"Exists",defaultValue:!1},show_messenger_webhook_errors:{type:"Exists",defaultValue:!1},is_go_live_modal_shown:{type:"Bool",defaultValue:!1},submission_id:{type:"FBID"},duc_app_ids:{type:"FBIDVector"},dev_listing_id:{type:"FBID"},phone_number_id:{type:"Int"},product_route:{type:"Enum",enumType:1},referring_message:{type:"FBID"},referring_source:{type:"String"}})}),null);
__d("XDeveloperAppController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/apps/{app_id}/{?page}/{?tab}/{?view}/",{business_id:{type:"Int"},sub_tab:{type:"String"},app_id:{type:"Int",required:!0},page:{type:"Enum",enumType:1},tab:{type:"String"},view:{type:"String"},use_case_enum:{type:"Enum",enumType:1},add_on_enum:{type:"Enum",enumType:1},placement_id:{type:"Int"},active_placements_offset:{type:"Int"},disabled_placements_offset:{type:"Int"},blocked_placements_offset:{type:"Int"},alert_id:{type:"Int"},ref:{type:"String"},id:{type:"Int"},app_locale:{type:"String"},a_n:{type:"String"},c_n:{type:"String"},access_token:{type:"String"},new_app_email_pending:{type:"Exists",defaultValue:!1},show_messenger_webhook_errors:{type:"Exists",defaultValue:!1},is_go_live_modal_shown:{type:"Bool",defaultValue:!1},submission_id:{type:"FBID"},duc_app_ids:{type:"FBIDVector"},dev_listing_id:{type:"FBID"},phone_number_id:{type:"Int"},product_route:{type:"Enum",enumType:1},referring_message:{type:"FBID"},referring_source:{type:"String"}})}),null);
__d("XBusinessUnifiedLoginPageController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/loginpage/",{option:{type:"Enum",enumType:1},next:{type:"String"},app:{type:"FBID"},login_options:{type:"EnumVector",enumType:{member:1}},cma_account_switch:{type:"Bool",defaultValue:!1},is_ig_oidc_with_redirect:{type:"Bool",defaultValue:!1},display:{type:"Enum",enumType:1},from_ig_login_upsell_sso:{type:"Bool",defaultValue:!1},is_work_accounts:{type:"Bool",defaultValue:!1},is_workplatform:{type:"Bool",defaultValue:!1},is_targeting_other_login_options:{type:"Bool",defaultValue:!1},from_shop_manager:{type:"Bool",defaultValue:!1},error_event:{type:"String"},delete_account:{type:"String"},invite_business_name:{type:"String"},from_ig_multi_admin_invite:{type:"Bool",defaultValue:!1},dnd_option:{type:"Enum",enumType:1},is_from_invitation_flow:{type:"Bool",defaultValue:!1},ig_user_name:{type:"String"},is_null_state:{type:"Bool",defaultValue:!1},is_ig_switching_account:{type:"Bool",defaultValue:!1},request_id:{type:"String"},config_ref:{type:"String"},is_igfa_graduation_account_switch:{type:"Bool",defaultValue:!1},is_logout_from_dfc:{type:"Bool",defaultValue:!1},show_back_button:{type:"Bool",defaultValue:!0},invite_join_id:{type:"String"}})}),null);
__d("XBusinessConsoleBaseViewController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/meta_business_admin_center/{?tab}/",{tab:{type:"Enum",enumType:1},one_click_claim:{type:"Bool",defaultValue:!1},unclaim_business_portfolios:{type:"Bool",defaultValue:!1},from_l6_entrypoint:{type:"Bool",defaultValue:!1},request_id:{type:"String"}})}),null);
__d("XDeveloperAppController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/apps/{app_id}/{?page}/{?tab}/{?view}/",{business_id:{type:"Int"},sub_tab:{type:"String"},app_id:{type:"Int",required:!0},page:{type:"Enum",enumType:1},tab:{type:"String"},view:{type:"String"},use_case_enum:{type:"Enum",enumType:1},add_on_enum:{type:"Enum",enumType:1},placement_id:{type:"Int"},active_placements_offset:{type:"Int"},disabled_placements_offset:{type:"Int"},blocked_placements_offset:{type:"Int"},alert_id:{type:"Int"},ref:{type:"String"},id:{type:"Int"},app_locale:{type:"String"},a_n:{type:"String"},c_n:{type:"String"},access_token:{type:"String"},new_app_email_pending:{type:"Exists",defaultValue:!1},show_messenger_webhook_errors:{type:"Exists",defaultValue:!1},is_go_live_modal_shown:{type:"Bool",defaultValue:!1},submission_id:{type:"FBID"},duc_app_ids:{type:"FBIDVector"},dev_listing_id:{type:"FBID"},phone_number_id:{type:"Int"},product_route:{type:"Enum",enumType:1},referring_message:{type:"FBID"},referring_source:{type:"String"}})}),null);
__d("IGXGenAIStudioBloksAsyncRawController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/async/wbloks/fetch/",{appid:{type:"String",required:!0},params:{type:"String"},type:{type:"Enum",required:!0,enumType:1},debug_tooling_metadata_token:{type:"String"}})}),null);
__d("XLeadGenGoogleSheetsHoldoutController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/ads/lead_gen/lead_download/google_sheets_holdout/",{page_id:{type:"Int"}})}),null);
__d("XBusinessFetchEnterpriseAccountController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/fetch_enterprise_account/",{})}),null);
__d("XBusinessEnterpriseEmailVerificationController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/enterprise/verification/email/",{nonce:{type:"String",required:!0}})}),null);
__d("XPagesSavedResponsesMediaDuplicationController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/pages/saved_responses/media/duplication/",{})}),null);

// old lines (count = 18)

__d("XWebBloksAsyncRawController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/async/wbloks/fetch/",{appid:{type:"String",required:!0},params:{type:"String"},type:{type:"Enum",required:!0,enumType:1}})}),null);
__d("XWebBloksAsyncRawController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/async/wbloks/fetch/",{appid:{type:"String",required:!0},params:{type:"String"},type:{type:"Enum",required:!0,enumType:1}})}),null);
__d("XWebBloksAsyncRawController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/async/wbloks/fetch/",{appid:{type:"String",required:!0},params:{type:"String"},type:{type:"Enum",required:!0,enumType:1}})}),null);
__d("XWebBloksAsyncRawController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/async/wbloks/fetch/",{appid:{type:"String",required:!0},params:{type:"String"},type:{type:"Enum",required:!0,enumType:1}})}),null);
__d("XWebBloksAsyncRawController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/async/wbloks/fetch/",{appid:{type:"String",required:!0},params:{type:"String"},type:{type:"Enum",required:!0,enumType:1}})}),null);
__d("XWebBloksAsyncRawController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/async/wbloks/fetch/",{appid:{type:"String",required:!0},params:{type:"String"},type:{type:"Enum",required:!0,enumType:1}})}),null);
__d("XBusinessUnifiedLoginPageController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/loginpage/",{option:{type:"Enum",enumType:1},next:{type:"String"},app:{type:"FBID"},login_options:{type:"EnumVector",enumType:{member:1}},cma_account_switch:{type:"Bool",defaultValue:!1},is_ig_oidc_with_redirect:{type:"Bool",defaultValue:!1},display:{type:"Enum",enumType:1},from_ig_login_upsell_sso:{type:"Bool",defaultValue:!1},is_work_accounts:{type:"Bool",defaultValue:!1},is_workplatform:{type:"Bool",defaultValue:!1},is_targeting_other_login_options:{type:"Bool",defaultValue:!1},from_shop_manager:{type:"Bool",defaultValue:!1},error_event:{type:"String"},delete_account:{type:"String"},invite_business_name:{type:"String"},from_ig_multi_admin_invite:{type:"Bool",defaultValue:!1},dnd_option:{type:"Enum",enumType:1},is_from_invitation_flow:{type:"Bool",defaultValue:!1},ig_user_name:{type:"String"},is_null_state:{type:"Bool",defaultValue:!1},is_ig_switching_account:{type:"Bool",defaultValue:!1},request_id:{type:"String"},config_ref:{type:"String"},is_igfa_graduation_account_switch:{type:"Bool",defaultValue:!1},is_logout_from_dfc:{type:"Bool",defaultValue:!1},show_back_button:{type:"Bool",defaultValue:!0}})}),null);
__d("XBusinessUnifiedLoginPageController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/business/loginpage/",{option:{type:"Enum",enumType:1},next:{type:"String"},app:{type:"FBID"},login_options:{type:"EnumVector",enumType:{member:1}},cma_account_switch:{type:"Bool",defaultValue:!1},is_ig_oidc_with_redirect:{type:"Bool",defaultValue:!1},display:{type:"Enum",enumType:1},from_ig_login_upsell_sso:{type:"Bool",defaultValue:!1},is_work_accounts:{type:"Bool",defaultValue:!1},is_workplatform:{type:"Bool",defaultValue:!1},is_targeting_other_login_options:{type:"Bool",defaultValue:!1},from_shop_manager:{type:"Bool",defaultValue:!1},error_event:{type:"String"},delete_account:{type:"String"},invite_business_name:{type:"String"},from_ig_multi_admin_invite:{type:"Bool",defaultValue:!1},dnd_option:{type:"Enum",enumType:1},is_from_invitation_flow:{type:"Bool",defaultValue:!1},ig_user_name:{type:"String"},is_null_state:{type:"Bool",defaultValue:!1},is_ig_switching_account:{type:"Bool",defaultValue:!1},request_id:{type:"String"},config_ref:{type:"String"},is_igfa_graduation_account_switch:{type:"Bool",defaultValue:!1},is_logout_from_dfc:{type:"Bool",defaultValue:!1},show_back_button:{type:"Bool",defaultValue:!0}})}),null);
__d("IGXGenAIStudioBloksAsyncRawController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/async/wbloks/fetch/",{appid:{type:"String",required:!0},params:{type:"String"},type:{type:"Enum",required:!0,enumType:1}})}),null);
__d("XDeveloperAppController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/apps/{app_id}/{?page}/{?tab}/{?view}/",{business_id:{type:"Int"},sub_tab:{type:"String"},app_id:{type:"Int",required:!0},page:{type:"Enum",enumType:1},tab:{type:"String"},view:{type:"String"},use_case_enum:{type:"Enum",enumType:1},add_on_enum:{type:"Enum",enumType:1},placement_id:{type:"Int"},active_placements_offset:{type:"Int"},disabled_placements_offset:{type:"Int"},blocked_placements_offset:{type:"Int"},alert_id:{type:"Int"},ref:{type:"String"},id:{type:"Int"},app_locale:{type:"String"},a_n:{type:"String"},c_n:{type:"String"},access_token:{type:"String"},new_app_email_pending:{type:"Exists",defaultValue:!1},show_messenger_webhook_errors:{type:"Exists",defaultValue:!1},is_go_live_modal_shown:{type:"Bool",defaultValue:!1},submission_id:{type:"FBID"},duc_app_ids:{type:"FBIDVector"},dev_listing_id:{type:"FBID"},phone_number_id:{type:"Int"},product_route:{type:"Enum",enumType:1}})}),null);
__d("XDeveloperAppController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/apps/{app_id}/{?page}/{?tab}/{?view}/",{business_id:{type:"Int"},sub_tab:{type:"String"},app_id:{type:"Int",required:!0},page:{type:"Enum",enumType:1},tab:{type:"String"},view:{type:"String"},use_case_enum:{type:"Enum",enumType:1},add_on_enum:{type:"Enum",enumType:1},placement_id:{type:"Int"},active_placements_offset:{type:"Int"},disabled_placements_offset:{type:"Int"},blocked_placements_offset:{type:"Int"},alert_id:{type:"Int"},ref:{type:"String"},id:{type:"Int"},app_locale:{type:"String"},a_n:{type:"String"},c_n:{type:"String"},access_token:{type:"String"},new_app_email_pending:{type:"Exists",defaultValue:!1},show_messenger_webhook_errors:{type:"Exists",defaultValue:!1},is_go_live_modal_shown:{type:"Bool",defaultValue:!1},submission_id:{type:"FBID"},duc_app_ids:{type:"FBIDVector"},dev_listing_id:{type:"FBID"},phone_number_id:{type:"Int"},product_route:{type:"Enum",enumType:1}})}),null);
__d("XBCMPCreatorSearchTypeaheadController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/branded_content/creator/typeahead/",{page_id:{type:"FBID",required:!0}})}),null);
__d("XWebPhotoEditCustomAccessibilityCaptionController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/photos/photo/custom_accessibility_caption/edit/",{})}),null);
__d("XWebPhotoEditCustomAccessibilityCaptionController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/photos/photo/custom_accessibility_caption/edit/",{})}),null);
__d("XBCMPCreatorSearchTypeaheadController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/branded_content/creator/typeahead/",{page_id:{type:"FBID",required:!0}})}),null);
__d("XBCMPCreatorSearchTypeaheadController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/branded_content/creator/typeahead/",{page_id:{type:"FBID",required:!0}})}),null);
__d("XDeveloperAppController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/apps/{app_id}/{?page}/{?tab}/{?view}/",{business_id:{type:"Int"},sub_tab:{type:"String"},app_id:{type:"Int",required:!0},page:{type:"Enum",enumType:1},tab:{type:"String"},view:{type:"String"},use_case_enum:{type:"Enum",enumType:1},add_on_enum:{type:"Enum",enumType:1},placement_id:{type:"Int"},active_placements_offset:{type:"Int"},disabled_placements_offset:{type:"Int"},blocked_placements_offset:{type:"Int"},alert_id:{type:"Int"},ref:{type:"String"},id:{type:"Int"},app_locale:{type:"String"},a_n:{type:"String"},c_n:{type:"String"},access_token:{type:"String"},new_app_email_pending:{type:"Exists",defaultValue:!1},show_messenger_webhook_errors:{type:"Exists",defaultValue:!1},is_go_live_modal_shown:{type:"Bool",defaultValue:!1},submission_id:{type:"FBID"},duc_app_ids:{type:"FBIDVector"},dev_listing_id:{type:"FBID"},phone_number_id:{type:"Int"},product_route:{type:"Enum",enumType:1}})}),null);
__d("XPagesSavedResponsesImageDuplicationController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/pages/saved_responses/image/duplication/",{})}),null);