name: fbtm-experimental
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  issues: write
jobs:
  issue_commented:
    name: process experimental comment
    if: ${{ !github.event.issue.pull_request && contains( github.event.issue.labels.*.name, 'experimental' ) }}
    runs-on: ubuntu-latest
    concurrency:
      group: fbtm-experimental
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: brxxn/fbtm-action@experimental
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
